name: Matrix Demo
on:
 push:
    branches:
      - dev
jobs:
  build:
    strategy:
      matrix:
        node-version: [18, 20]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enable yarn
        run: corepack enable
      - name: Install deps
        run: yarn
      - name: Build
        run: yarn build
