name: Test Project
on: [push, workflow_dispatch]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2

      - name: Enable yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - name: Validate types
        run: yarn check-ts

      - name: Validate lint
        run: yarn check-lint

      - name: Validate tests
        run: yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: validation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2

      - name: Enable yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy
        run: echo "Deploying build"
