name: Test Project
on: [push, workflow_dispatch]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
      - name: Enable yarn
        run: corepack enable
      - name: Install dependencies
        run: yarn
      - name: Validate types
        run: yarn check-ts
      - name: Validate lint
        run: yarn check-lint
      - name: Validate tests
        run: yarn test

  build:
    runs-on: ubuntu-latest
    needs: validation
    outputs:
      artifact-id: ${{ steps.upload-dist.outputs.artifact-id }}
      artifact-url: ${{ steps.upload-dist.outputs.artifact-url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
      - name: Enable yarn
        run: corepack enable
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Publish file names
        run: find dist/assets/*.js -type f -execdir echo '{}' ';'
      - name: Upload artifacts
        id: upload-dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print outputs
        run: |
          echo ${{ needs.build.outputs.artifact-id  }}
          echo ${{ needs.build.outputs.artifact-url  }}
      - uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Display structure of downloaded files
        run: ls -R .
